"""A worked example of a pilot record, fabricated and labelled as such in its data.

It shows the shape of a record. It is not a reviewer session: the reviewer id is the
one reserved for synthetic examples, the evidence class excludes it from every
summary, and each free-text field says what it is. Timestamps are fixed so the
committed files can be regenerated byte for byte.

Run `python -m src.pilot_example` to rewrite examples/pilot/synthetic-worked-example/.
"""

from __future__ import annotations

from pathlib import Path

from models import MatterIntake
from src.pilot_record import PilotRecord, build_pilot_record, write_pilot_record
from src.pilot_session import (
    SYNTHETIC_REVIEWER_ID,
    close_review_session,
    mark_draft_reviewable,
    prepare_review_draft,
    record_change_decision,
    record_material_omission,
    start_review_session,
)

FIXTURE = Path("examples/matters/saas_msa_deviation.json")
OUTPUT_DIR = Path("examples/pilot/synthetic-worked-example")
LABEL = "SYNTHETIC EXAMPLE, not a reviewer's view."


def build_example_record() -> PilotRecord:
    intake = MatterIntake.model_validate_json(FIXTURE.read_text(encoding="utf-8"))
    matter = intake.model_copy(
        update={"matter_id": "synthetic-worked-example", "round_id": "example"}
    )
    draft = prepare_review_draft(
        matter, intake_at="2026-01-01T09:00:00Z", ready_at="2026-01-01T09:00:01Z"
    )
    session = start_review_session(
        draft,
        reviewer_id=SYNTHETIC_REVIEWER_ID,
        evidence_class="synthetic_example",
        reviewer_profile=f"{LABEL} No person reviewed anything.",
        at="2026-01-01T10:00:00Z",
    )
    first, second = (change.id for change in draft.change_set.changes)
    session = record_change_decision(
        session,
        change_id=first,
        decision="corrected",
        usefulness=3,
        reason=f"{LABEL} Placeholder for the reason a correction requires.",
        corrected_text=f"{LABEL} Placeholder for the reviewer's replacement wording.",
        at="2026-01-01T10:10:00Z",
    )
    session = mark_draft_reviewable(session, at="2026-01-01T10:15:00Z")
    session = record_change_decision(
        session,
        change_id=second,
        decision="rejected",
        usefulness=2,
        reason=f"{LABEL} Placeholder for the reason a rejection requires.",
        at="2026-01-01T10:20:00Z",
    )
    session = record_material_omission(
        session,
        text=f"{LABEL} Placeholder for an issue the draft missed.",
        at="2026-01-01T10:25:00Z",
    )
    session = close_review_session(
        session,
        state="revision_requested",
        note=f"{LABEL} Placeholder for the note a decision on the matter requires.",
        workflow_feedback=f"{LABEL} Placeholder for feedback on the workflow.",
        at="2026-01-01T10:30:00Z",
    )
    return build_pilot_record(draft, [session], generated_at="2026-01-01T11:00:00Z")


def main() -> None:
    json_path, markdown_path = write_pilot_record(build_example_record(), OUTPUT_DIR)
    print(f"wrote {json_path} and {markdown_path}")


if __name__ == "__main__":
    main()
